package pl.polsl.acsupport.bootstraping.enums;

public enum BootStrapingLabel {
    CREATE_DEFAULT_BUILDINGS,
    CREATE_DEFAULT_USERS,
    CREATE_DEFAULT_ROLES,
    CREATE_DEFAULT_BUILDING_TYPES,
    ASSIGN_DEFAULT_BUILDING_TYPES_TO_BUILDINGS,
    CREATE_DEFAULT_ROOMS,
    ASSIGN_USER_TO_ROLES,
    ASSIGN_DEFAULT_USERS_TO_DEFAULT_BUILDINGS,
    ASSING_DEFAULT_ROOM_TO_BUILDINGS,
    CREATE_DEFAULT_ROOM_TYPES,
    ASSING_DEFAULT_ROOM_TYPES_TO_ROOMS,
}
