package pl.polsl.acsupport.enums;

public enum PermissionName {
    FIND_BUILDING,
    CREATE_BUILDING,
    UPDATE_BUILDING,
    DELETE_BUILDING,
    FIND_BUILDING_TYPE,
    CREATE_BUILDING_TYPE,
    DELETE_BUILDING_TYPE,
    FIND_ROOM,
    CREATE_ROOM,
    UPDATE_ROOM,
    DELETE_ROOM,
    FIND_USER,
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,
    FIND_ROOM_TYPE,
    CREATE_ROOM_TYPE,
    DELETE_ROOM_TYPE,
    FIND_MESSAGES,
    CREATE_MESSAGE,

}
